/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 scene.gltf
Author: Tabbuso (https://sketchfab.com/Tabbuso)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tshirt-5a21282b2e454d1696547148f617d3d0
Title: Tshirt
*/

import React, { useRef } from 'react';
import { useFrame } from '@react-three/fiber';
import { Decal, useGLTF, useTexture } from '@react-three/drei';
import { useSnapshot } from 'valtio';
import { easing } from 'maath';
import state from '../../store';

export function TshirtModel(props) {
	const snap = useSnapshot(state);
	const ref = useRef();

	const { nodes, materials } = useGLTF('/tshirt/scene.gltf');
	const logoTexture = useTexture(snap.logoDecal);
	const fullTexture = useTexture(snap.fullDecal);

	useFrame((state, delta) => {
		easing.dampC(
			materials['FABRIC_1_FRONT_4193'].color,
			snap.color,
			0.25,
			delta
		);
	});
	return (
		<group
			{...props}
			ref={ref}
			key={JSON.stringify(snap)}
			dispose={null}
			rotation={[Math.PI / 2, 0, 0]}
			scale={0.0011}>
			<mesh
				geometry={nodes.Object_4.geometry}
				material={materials.FABRIC_1_FRONT_4193}
				castShadow
				material-rougeness={0.1}
			/>
			<mesh
				geometry={nodes.Object_5.geometry}
				material={materials.FABRIC_1_FRONT_4193}
				castShadow
				material-rougeness={0.1}
			/>
			<mesh
				geometry={nodes.Object_6.geometry}
				material={materials.FABRIC_1_FRONT_4193}
				castShadow
				material-rougeness={0.1}
			/>
			<mesh
				geometry={nodes.Object_7.geometry}
				material={materials.FABRIC_1_FRONT_4193}
				castShadow
				material-rougeness={0.1}
			/>
		</group>
	);
}
